undefined [31merror[39m : [Erreur Enregistrement product] Sauvegarde db error: insert into "product" ("collection_id", "img", "name", "packaging_id", "performance_id", "price", "product_id", "property_id", "stock") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "id" - la colonne Â« id Â» n'existe pas
    at Parser.parseErrorMessage (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/fanch/admin/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 110,
  severity: 'ERREUR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '191',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3514',
  routine: 'errorMissingColumn'
}
undefined [31merror[39m : [Erreur Enregistrement product] Sauvegarde db error: insert into "product" ("collection_id", "img", "name", "packaging_id", "performance_id", "price", "product_id", "property_id", "stock") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "product_id" - la valeur d'une clÃ© dupliquÃ©e rompt la contrainte unique Â« product_pk Â»
    at Parser.parseErrorMessage (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/fanch/admin/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 217,
  severity: 'ERREUR',
  code: '23505',
  detail: 'La clÃ© Â« (product_id)=(42) Â» existe dÃ©jÃ .',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'product',
  column: undefined,
  dataType: undefined,
  constraint: 'product_pk',
  file: 'nbtinsert.c',
  line: '656',
  routine: '_bt_check_unique'
}
undefined [31merror[39m : [Erreur Enregistrement product] Sauvegarde db error: insert into "product" ("collection_id", "img", "name", "packaging_id", "performance_id", "price", "product_id", "property_id", "stock") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "product_id" - la valeur d'une clÃ© dupliquÃ©e rompt la contrainte unique Â« product_pk Â»
    at Parser.parseErrorMessage (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/fanch/admin/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 216,
  severity: 'ERREUR',
  code: '23505',
  detail: 'La clÃ© Â« (product_id)=(5) Â» existe dÃ©jÃ .',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'product',
  column: undefined,
  dataType: undefined,
  constraint: 'product_pk',
  file: 'nbtinsert.c',
  line: '656',
  routine: '_bt_check_unique'
}
undefined [31merror[39m : [Erreur Enregistrement customer] Sauvegarde db error: insert into "customer" ("address", "city", "collection_id", "firstname", "mail", "name", "postal") values ($1, $2, $3, $4, $5, $6, $7) on conflict ("user_id") do update set "address" = excluded."address", "city" = excluded."city", "collection_id" = excluded."collection_id", "firstname" = excluded."firstname", "mail" = excluded."mail", "name" = excluded."name", "postal" = excluded."postal" returning "user_id" - la colonne Â« collection_id Â» de la relation Â« customer Â» n'existe pas
    at Parser.parseErrorMessage (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/fanch/admin/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 148,
  severity: 'ERREUR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '44',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1039',
  routine: 'checkInsertTargets'
}
undefined [31merror[39m : [Erreur Enregistrement customer] Sauvegarde db error: insert into "customer" ("address", "city", "collection_id", "country", "firstname", "mail", "name", "postal") values ($1, $2, $3, $4, $5, $6, $7, $8) on conflict ("user_id") do update set "address" = excluded."address", "city" = excluded."city", "collection_id" = excluded."collection_id", "country" = excluded."country", "firstname" = excluded."firstname", "mail" = excluded."mail", "name" = excluded."name", "postal" = excluded."postal" returning "user_id" - la colonne Â« collection_id Â» de la relation Â« customer Â» n'existe pas
    at Parser.parseErrorMessage (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/fanch/admin/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 148,
  severity: 'ERREUR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '44',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1039',
  routine: 'checkInsertTargets'
}
undefined [31merror[39m : [Erreur Enregistrement customer] Sauvegarde db error: insert into "customer" ("address", "city", "country", "firstname", "mail", "name", "postal") values ($1, $2, $3, $4, $5, $6, $7) on conflict ("user_id") do update set "address" = excluded."address", "city" = excluded."city", "country" = excluded."country", "firstname" = excluded."firstname", "mail" = excluded."mail", "name" = excluded."name", "postal" = excluded."postal" returning "user_id" - une valeur NULL viole la contrainte NOT NULL de la colonne Â« user_id Â» dans la relation Â« customer Â»
    at Parser.parseErrorMessage (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/fanch/admin/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/fanch/admin/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 316,
  severity: 'ERREUR',
  code: '23502',
  detail: "La ligne en Ã©chec contient (null, Cavellec, Fanch, 1 rue d'aubignÃ©, 35440, fanch44@hotmail.com, Feins, France, null).",
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'customer',
  column: 'user_id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1953',
  routine: 'ExecConstraints'
}
